# Generated by Django 6.0.3 on 2026-03-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=500)),
                ('thumbnail_small_url', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_medium_url', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail_large_url', models.URLField(blank=True, max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('rock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rockapi.rock')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
